/* Dev Shree Saini — translations (English → German, French)

   HOW IT WORKS
   Every translatable element in index.html carries a `data-i18n` attribute.
   Its English text is the lookup key below; the value is [German, French].
   Text generated by js/main.js (project pop-ups) and js/globe.js (globe list)
   is looked up the same way through window.i18n.t().

   EDITING
   - Change English text in index.html → change the matching key here too,
     otherwise that one element simply stays in English.
   - Keys are compared with whitespace collapsed, so line breaks don't matter.
   - Values may contain inline HTML (<strong>, <em>, <a …>) where the English does.
   - Strings that are the same in every language go in I18N_SAME.

   Works when index.html is opened straight from disk — no server needed. */

const I18N_DICT = {
    // ---------- navigation, loader, hero ----------
    [`Skip to content`]: [`Zum Inhalt springen`, `Aller au contenu`],
    [`Earth Observation · Geospatial Machine Learning`]: [`Erdbeobachtung · Maschinelles Lernen für Geodaten`, `Observation de la Terre · Apprentissage automatique géospatial`],
    [`About`]: [`Über mich`, `À propos`],
    [`Skills`]: [`Kompetenzen`, `Compétences`],
    [`Experience`]: [`Erfahrung`, `Expérience`],
    [`Work`]: [`Projekte`, `Projets`],
    [`Research`]: [`Forschung`, `Recherche`],
    [`Background`]: [`Werdegang`, `Parcours`],
    [`Contact`]: [`Kontakt`, `Contact`],
    [`Light`]: [`Hell`, `Clair`],
    [`Dark`]: [`Dunkel`, `Sombre`],
    [`Earth Observation · Geospatial Machine Learning · ETH Zurich`]: [`Erdbeobachtung · Maschinelles Lernen für Geodaten · ETH Zürich`, `Observation de la Terre · Apprentissage automatique géospatial · ETH Zurich`],
    [`Zurich, Switzerland`]: [`Zürich, Schweiz`, `Zurich, Suisse`],
    [`Download Resume`]: [`Lebenslauf herunterladen`, `Télécharger le CV`],
    [`Contact Me`]: [`Kontakt aufnehmen`, `Me contacter`],
    [`MSc Geomatics, ETH Zurich`]: [`MSc Geomatik, ETH Zürich`, `Master en géomatique, ETH Zurich`],
    [`Graduating March 2027`]: [`Abschluss im März 2027`, `Diplôme prévu en mars 2027`],
    [`Research Intern, RSL — UZH`]: [`Forschungspraktikant, RSL — UZH`, `Stagiaire de recherche, RSL — UZH`],
    [`ESA-funded hyperspectral project`]: [`ESA-finanziertes Hyperspektralprojekt`, `Projet hyperspectral financé par l'ESA`],
    [`Based in Zurich, Switzerland`]: [`Wohnhaft in Zürich, Schweiz`, `Basé à Zurich, Suisse`],
    [`Open to relocation within Europe`]: [`Offen für einen Umzug innerhalb Europas`, `Ouvert à une mobilité en Europe`],
    [`Open to`]: [`Offen für`, `Ouvert à`],
    [`EO / geospatial ML roles, research collaborations, thesis partnerships`]: [`Stellen in Erdbeobachtung und Geodaten-ML, Forschungskooperationen, Partnerschaften für Abschlussarbeiten`, `Postes en observation de la Terre et ML géospatial, collaborations de recherche, partenariats de mémoire`],
    [`Geomatics Master's student at ETH Zurich, working on Earth observation, geospatial machine learning, and environmental monitoring. Experienced in satellite data processing, deep learning for remote sensing, and building Python-based spatial modelling pipelines. Interested in applying Earth observation and machine learning to real-world environmental problems, from flood monitoring to ecosystem mapping.`]: [
        `Masterstudent der Geomatik an der ETH Zürich mit Schwerpunkt auf Erdbeobachtung, maschinellem Lernen für Geodaten und Umweltmonitoring. Erfahrung in der Verarbeitung von Satellitendaten, Deep Learning für die Fernerkundung und im Aufbau Python-basierter Pipelines für räumliche Modellierung. Mein Ziel ist es, Erdbeobachtung und maschinelles Lernen auf reale Umweltprobleme anzuwenden – von der Hochwasserüberwachung bis zur Kartierung von Ökosystemen.`,
        `Étudiant en master de géomatique à l'ETH Zurich, je travaille sur l'observation de la Terre, l'apprentissage automatique géospatial et la surveillance environnementale. J'ai de l'expérience dans le traitement de données satellitaires, l'apprentissage profond pour la télédétection et la création de pipelines de modélisation spatiale en Python. Je souhaite appliquer l'observation de la Terre et l'apprentissage automatique à des problèmes environnementaux concrets, du suivi des inondations à la cartographie des écosystèmes.`],
    [`Journal Papers`]: [`Fachartikel`, `Articles de revue`],
    [`First-Author Papers`]: [`Als Erstautor`, `En premier auteur`],
    [`Conference Presentations`]: [`Konferenzvorträge`, `Présentations en conférence`],

    // ---------- about ----------
    [`ABOUT ME`]: [`ÜBER MICH`, `À PROPOS DE MOI`],
    [`Geospatial Vision`]: [`Vision`, `Vision`],
    [`Satellite data already holds a lot of the answers we need on climate change, but most of it stays locked in formats and pipelines only specialists can use. I want to help close that gap, so this information is easier to reach and use by more people, not just researchers.`]: [
        `Satellitendaten enthalten bereits viele der Antworten, die wir zum Klimawandel brauchen – doch der Grossteil bleibt in Formaten und Pipelines verborgen, die nur Fachleute nutzen können. Ich möchte helfen, diese Lücke zu schliessen, damit diese Informationen für mehr Menschen zugänglich und nutzbar werden, nicht nur für Forschende.`,
        `Les données satellitaires contiennent déjà une grande partie des réponses dont nous avons besoin face au changement climatique, mais la plupart restent enfermées dans des formats et des chaînes de traitement que seuls les spécialistes savent utiliser. Je veux contribuer à combler ce fossé, afin que ces informations soient plus faciles d'accès et d'usage pour un plus grand nombre, et pas seulement pour les chercheurs.`],
    [`Research Focus`]: [`Forschungsschwerpunkt`, `Axes de recherche`],
    [`I work on machine learning for geospatial data, with a particular interest in Earth observation and natural hazards. My work combines satellite and airborne data with physical models to understand how the ground, ice, and ecosystems around us change. A lot of it sits between physics-based simulation and machine learning, using one to make the other faster and more usable at scale.`]: [
        `Ich arbeite an maschinellem Lernen für Geodaten, mit besonderem Interesse an Erdbeobachtung und Naturgefahren. Meine Arbeit verbindet Satelliten- und Flugzeugdaten mit physikalischen Modellen, um zu verstehen, wie sich Boden, Eis und Ökosysteme um uns herum verändern. Vieles davon liegt zwischen physikbasierter Simulation und maschinellem Lernen – das eine wird genutzt, um das andere schneller und im grossen Massstab nutzbar zu machen.`,
        `Je travaille sur l'apprentissage automatique appliqué aux données géospatiales, avec un intérêt particulier pour l'observation de la Terre et les risques naturels. Mes travaux combinent des données satellitaires et aéroportées avec des modèles physiques pour comprendre comment le sol, la glace et les écosystèmes qui nous entourent évoluent. Une grande partie se situe entre la simulation physique et l'apprentissage automatique, en utilisant l'une pour rendre l'autre plus rapide et plus exploitable à grande échelle.`],

    // ---------- news ----------
    [`NEWS`]: [`NEUIGKEITEN`, `ACTUALITÉS`],
    [`Jul 2026`]: [`Juli 2026`, `juil. 2026`],
    [`Mar 2026`]: [`März 2026`, `mars 2026`],
    [`Dec 2025`]: [`Dez. 2025`, `déc. 2025`],
    [`Sep 2025`]: [`Sept. 2025`, `sept. 2025`],
    [`Mar 2025`]: [`März 2025`, `mars 2025`],
    [`Sep 2024`]: [`Sept. 2024`, `sept. 2024`],
    [`Mar 2024`]: [`März 2024`, `mars 2024`],
    [`Aug 2023`]: [`Aug. 2023`, `août 2023`],
    [`May 2023`]: [`Mai 2023`, `mai 2023`],
    [`Jan 2023`]: [`Jan. 2023`, `janv. 2023`],
    [`Jun 2022`]: [`Juni 2022`, `juin 2022`],
    [`Mar 2022`]: [`März 2022`, `mars 2022`],
    [`Sep 2021`]: [`Sept. 2021`, `sept. 2021`],
    [`Jul 2019`]: [`Juli 2019`, `juil. 2019`],
    [`Started as a Research Intern at the Remote Sensing Laboratories, University of Zurich, on an ESA-funded hyperspectral environmental monitoring project.`]: [
        `Start als Forschungspraktikant an den <strong>Remote Sensing Laboratories der Universität Zürich</strong> in einem ESA-finanzierten Projekt zum hyperspektralen Umweltmonitoring.`,
        `Début d'un stage de recherche aux <strong>Remote Sensing Laboratories de l'Université de Zurich</strong>, sur un projet de surveillance environnementale hyperspectrale financé par l'ESA.`],
    [`MapSAM2 published in IEEE Transactions on Geoscience and Remote Sensing: adapting the SAM2 foundation model to historical map segmentation. DOI`]: [
        `<strong>MapSAM2</strong> in <em>IEEE Transactions on Geoscience and Remote Sensing</em> veröffentlicht: Anpassung des Foundation Models SAM2 an die Segmentierung historischer Karten. <a href="https://doi.org/10.1109/TGRS.2026.3678420" target="_blank" rel="noopener" class="news-link">DOI</a>`,
        `<strong>MapSAM2</strong> publié dans <em>IEEE Transactions on Geoscience and Remote Sensing</em> : adaptation du modèle de fondation SAM2 à la segmentation de cartes historiques. <a href="https://doi.org/10.1109/TGRS.2026.3678420" target="_blank" rel="noopener" class="news-link">DOI</a>`],
    [`Presented heavy-precipitation detection from GNSS Zenith Wet Delay at the Swiss Geoscience Meeting, Bern.`]: [
        `Vortrag zur Erkennung von Starkniederschlägen aus dem GNSS Zenith Wet Delay am <strong>Swiss Geoscience Meeting</strong> in Bern.`,
        `Présentation sur la détection des fortes précipitations à partir du retard humide zénithal GNSS au <strong>Swiss Geoscience Meeting</strong>, à Berne.`],
    [`Joined the Space Geodesy group at ETH Zurich as a Research Assistant.`]: [
        `Eintritt in die <strong>Gruppe für Weltraumgeodäsie der ETH Zürich</strong> als wissenschaftlicher Assistent.`,
        `Arrivée dans le <strong>groupe de géodésie spatiale de l'ETH Zurich</strong> en tant qu'assistant de recherche.`],
    [`First-author paper on land use/cover dynamics and ecosystem service values published in Estuaries and Coasts. DOI`]: [
        `Artikel als Erstautor zu Landnutzungsdynamik und Ökosystemleistungen in <em>Estuaries and Coasts</em> veröffentlicht. <a href="https://doi.org/10.1007/s12237-025-01509-0" target="_blank" rel="noopener" class="news-link">DOI</a>`,
        `Article en premier auteur sur la dynamique de l'occupation des sols et la valeur des services écosystémiques publié dans <em>Estuaries and Coasts</em>. <a href="https://doi.org/10.1007/s12237-025-01509-0" target="_blank" rel="noopener" class="news-link">DOI</a>`],
    [`Began the MSc in Geomatics Engineering at ETH Zurich.`]: [
        `Beginn des <strong>MSc in Geomatik an der ETH Zürich</strong>.`,
        `Début du <strong>master en géomatique à l'ETH Zurich</strong>.`],
    [`First-author paper on HEC-RAS flood modelling published in the Journal of the Geological Society of India. DOI`]: [
        `Artikel als Erstautor zur Hochwassermodellierung mit HEC-RAS im <em>Journal of the Geological Society of India</em> veröffentlicht. <a href="https://doi.org/10.17491/jgsi/2024/173843" target="_blank" rel="noopener" class="news-link">DOI</a>`,
        `Article en premier auteur sur la modélisation des crues avec HEC-RAS publié dans le <em>Journal of the Geological Society of India</em>. <a href="https://doi.org/10.17491/jgsi/2024/173843" target="_blank" rel="noopener" class="news-link">DOI</a>`],
    [`Co-authored paper on short-duration precipitation in the Cauvery Basin published in Scientific Reports. DOI`]: [
        `Mitverfasster Artikel zu kurzzeitigen Niederschlagsereignissen im Cauvery-Becken in <em>Scientific Reports</em> veröffentlicht. <a href="https://doi.org/10.1038/s41598-023-41417-6" target="_blank" rel="noopener" class="news-link">DOI</a>`,
        `Article co-écrit sur les précipitations de courte durée dans le bassin de la Cauvery publié dans <em>Scientific Reports</em>. <a href="https://doi.org/10.1038/s41598-023-41417-6" target="_blank" rel="noopener" class="news-link">DOI</a>`],
    [`Graduated with a BTech in Civil Engineering from VIT Vellore: ranked 2nd in the department and named Best Outgoing Student.`]: [
        `Abschluss des <strong>BTech in Bauingenieurwesen am VIT Vellore</strong>: Rang 2 im Studiengang und als bester Absolvent ausgezeichnet.`,
        `Diplômé d'un <strong>BTech en génie civil du VIT Vellore</strong> : 2e du département et distingué meilleur diplômé.`],
    [`Presented wetland discharge filtration research at the CSCE Annual Conference 2023, Moncton, Canada.`]: [
        `Vortrag zur Filtration von Feuchtgebietsabflüssen an der <strong>CSCE Annual Conference 2023</strong> in Moncton, Kanada.`,
        `Présentation de travaux sur la filtration des eaux de rejet de zones humides à la <strong>CSCE Annual Conference 2023</strong>, à Moncton, Canada.`],
    [`Began a Spatial Data Analyst internship at IIRS, ISRO, Dehradun.`]: [
        `Beginn eines Praktikums als Spatial Data Analyst am <strong>IIRS, ISRO</strong> in Dehradun.`,
        `Début d'un stage d'analyste de données spatiales à l'<strong>IIRS, ISRO</strong>, à Dehradun.`],
    [`Began a MITACS Globalink Research Internship at Concordia University, Montreal.`]: [
        `Beginn eines <strong>MITACS Globalink Research Internship</strong> an der Concordia University in Montreal.`,
        `Début d'un <strong>stage de recherche MITACS Globalink</strong> à l'Université Concordia, à Montréal.`],
    [`Presented flood-prone zone mapping with HEC-RAS at the Roorkee Water Conclave 2022.`]: [
        `Vortrag zur Kartierung hochwassergefährdeter Gebiete mit HEC-RAS am <strong>Roorkee Water Conclave 2022</strong>.`,
        `Présentation sur la cartographie des zones inondables avec HEC-RAS au <strong>Roorkee Water Conclave 2022</strong>.`],
    [`Began as a Teaching Assistant at VIT Vellore, supporting three PhD research projects.`]: [
        `Beginn als Lehrassistent am VIT Vellore mit Unterstützung von drei Doktorandenprojekten.`,
        `Début en tant qu'assistant d'enseignement au VIT Vellore, en appui à trois projets de doctorat.`],
    [`Began the BTech in Civil Engineering at VIT Vellore.`]: [
        `Beginn des <strong>BTech in Bauingenieurwesen am VIT Vellore</strong>.`,
        `Début du <strong>BTech en génie civil au VIT Vellore</strong>.`],
    [`Scroll for older news`]: [`Für ältere Neuigkeiten scrollen`, `Faites défiler pour les actualités plus anciennes`],

    // ---------- explainer ----------
    [`New to geospatial engineering?`]: [`Neu in der Geomatik?`, `Nouveau dans l'ingénierie géospatiale ?`],
    [`Open a short explainer of what the field covers.`]: [`Eine kurze Einführung in das Fachgebiet öffnen.`, `Ouvrir une brève présentation du domaine.`],
    [`WHAT IS GEOSPATIAL ENGINEERING?`]: [`WAS IST GEOMATIK?`, `QU'EST-CE QUE L'INGÉNIERIE GÉOSPATIALE ?`],
    [`Turning satellite measurements into maps people can act on.`]: [`Aus Satellitenmessungen werden Karten, auf deren Grundlage Menschen handeln können.`, `Transformer des mesures satellitaires en cartes sur lesquelles on peut agir.`],
    [`Satellite Data`]: [`Satellitendaten`, `Données satellitaires`],
    [`Like a doctor uses X-rays to see inside the body, we use satellite images to see Earth's health from space. We process data from various satellite sensors (optical, radar, LiDAR) to monitor environmental changes, track deforestation, measure sea level rise, and detect urban expansion.`]: [
        `So wie Ärztinnen und Ärzte mit Röntgenbildern in den Körper schauen, nutzen wir Satellitenbilder, um den Zustand der Erde aus dem All zu beurteilen. Wir verarbeiten Daten verschiedener Satellitensensoren (optisch, Radar, LiDAR), um Umweltveränderungen zu beobachten, Entwaldung zu verfolgen, den Meeresspiegelanstieg zu messen und das Wachstum von Städten zu erkennen.`,
        `Comme un médecin utilise les rayons X pour voir à l'intérieur du corps, nous utilisons les images satellites pour observer la santé de la Terre depuis l'espace. Nous traitons les données de différents capteurs satellitaires (optiques, radar, LiDAR) pour suivre les changements environnementaux, la déforestation, la montée du niveau de la mer et l'expansion urbaine.`],
    [`Mapping & Analysis`]: [`Kartierung & Analyse`, `Cartographie et analyse`],
    [`Think of Google Maps, but with superpowers to predict floods, track deforestation, and monitor climate change. We create intelligent maps that help understand complex environmental patterns, analyze spatial relationships, and make data-driven decisions for sustainable development.`]: [
        `Wie Google Maps, aber mit Superkräften: Hochwasser vorhersagen, Entwaldung verfolgen und den Klimawandel beobachten. Wir erstellen intelligente Karten, die helfen, komplexe Umweltmuster zu verstehen, räumliche Zusammenhänge zu analysieren und datenbasierte Entscheidungen für eine nachhaltige Entwicklung zu treffen.`,
        `Comme Google Maps, mais avec des super-pouvoirs : prévoir les inondations, suivre la déforestation et surveiller le changement climatique. Nous créons des cartes intelligentes qui aident à comprendre des phénomènes environnementaux complexes, à analyser les relations spatiales et à prendre des décisions fondées sur les données pour un développement durable.`],
    [`AI Solutions`]: [`KI-Lösungen`, `Solutions d'IA`],
    [`Similar to facial recognition, but for Earth's features - identifying floods, droughts, and urban growth patterns. We train computers to automatically detect environmental changes from satellite data using deep learning models like CNNs and transformers, enabling real-time monitoring at global scales.`]: [
        `Ähnlich wie Gesichtserkennung, nur für Merkmale der Erde – Hochwasser, Dürren und Stadtwachstum erkennen. Wir trainieren Computer darauf, Umweltveränderungen mit Deep-Learning-Modellen wie CNNs und Transformern automatisch in Satellitendaten zu erkennen, und ermöglichen so eine Echtzeitüberwachung im globalen Massstab.`,
        `Comme la reconnaissance faciale, mais pour les éléments de la surface terrestre : identifier les inondations, les sécheresses et la croissance urbaine. Nous entraînons des ordinateurs à détecter automatiquement les changements environnementaux dans les données satellitaires grâce à des modèles d'apprentissage profond comme les CNN et les transformers, pour une surveillance en temps réel à l'échelle mondiale.`],
    [`Why It Matters`]: [`Warum es wichtig ist`, `Pourquoi c'est important`],
    [`Geospatial engineering helps solve some of the world's most pressing challenges:`]: [`Geomatik hilft, einige der dringendsten Herausforderungen der Welt zu lösen:`, `L'ingénierie géospatiale aide à relever certains des défis les plus urgents de la planète :`],
    [`Predicting natural disasters before they happen`]: [`Naturkatastrophen vorhersagen, bevor sie eintreten`, `Prévoir les catastrophes naturelles avant qu'elles ne surviennent`],
    [`Monitoring climate change impacts in real-time`]: [`Folgen des Klimawandels in Echtzeit überwachen`, `Suivre les effets du changement climatique en temps réel`],
    [`Optimizing renewable energy deployment`]: [`Den Ausbau erneuerbarer Energien optimieren`, `Optimiser le déploiement des énergies renouvelables`],
    [`Protecting endangered ecosystems`]: [`Gefährdete Ökosysteme schützen`, `Protéger les écosystèmes menacés`],
    [`Improving urban planning for sustainable cities`]: [`Stadtplanung für nachhaltige Städte verbessern`, `Améliorer l'urbanisme pour des villes durables`],
    [`Real-World Example`]: [`Praxisbeispiel`, `Exemple concret`],
    [`When a flood occurs, our systems can automatically detect the affected areas from satellite images within hours, helping emergency responders save lives and allocate resources efficiently.`]: [
        `Wenn ein Hochwasser auftritt, können unsere Systeme die betroffenen Gebiete innerhalb weniger Stunden automatisch in Satellitenbildern erkennen – und so Einsatzkräften helfen, Leben zu retten und Ressourcen gezielt einzusetzen.`,
        `Lorsqu'une inondation survient, nos systèmes peuvent détecter automatiquement les zones touchées sur les images satellites en quelques heures, aidant les secours à sauver des vies et à répartir efficacement les ressources.`],
    [`That's what I work on!`]: [`Genau daran arbeite ich!`, `C'est exactement ce sur quoi je travaille !`],

    // ---------- skills ----------
    [`TECHNICAL SKILLS`]: [`TECHNISCHE KOMPETENZEN`, `COMPÉTENCES TECHNIQUES`],
    [`Programming`]: [`Programmierung`, `Programmation`],
    [`Machine Learning`]: [`Maschinelles Lernen`, `Apprentissage automatique`],
    [`Earth Observation`]: [`Erdbeobachtung`, `Observation de la Terre`],
    [`Sentinel-1/2, EnMAP, SAR, Hyperspectral`]: [`Sentinel-1/2, EnMAP, SAR, Hyperspektral`, `Sentinel-1/2, EnMAP, SAR, hyperspectral`],
    [`Weather & Reanalysis`]: [`Wetter & Reanalyse`, `Météo et réanalyse`],
    [`GIS & Geospatial`]: [`GIS & Geodaten`, `SIG et géospatial`],
    [`Data Analysis`]: [`Datenanalyse`, `Analyse de données`],
    [`xarray, Time-Series Forecasting, Benchmarking`]: [`xarray, Zeitreihenprognose, Benchmarking`, `xarray, prévision de séries temporelles, benchmarking`],
    [`Hydrological Modelling`]: [`Hydrologische Modellierung`, `Modélisation hydrologique`],
    [`HEC-RAS, Arc-SWAT, Flood Risk`]: [`HEC-RAS, Arc-SWAT, Hochwasserrisiko`, `HEC-RAS, Arc-SWAT, risque d'inondation`],
    [`Scientific Computing`]: [`Wissenschaftliches Rechnen`, `Calcul scientifique`],
    [`Large-Scale Pipelines, Multi-sensor Processing, Scientific Writing`]: [`Grossskalige Pipelines, Multisensor-Verarbeitung, wissenschaftliches Schreiben`, `Pipelines à grande échelle, traitement multi-capteurs, rédaction scientifique`],

    // ---------- experience ----------
    [`PROFESSIONAL EXPERIENCE`]: [`BERUFSERFAHRUNG`, `EXPÉRIENCE PROFESSIONNELLE`],
    [`Research Intern`]: [`Forschungspraktikant`, `Stagiaire de recherche`],
    [`Remote Sensing Laboratories, University of Zurich`]: [`Remote Sensing Laboratories, Universität Zürich`, `Remote Sensing Laboratories, Université de Zurich`],
    [`Current role`]: [`Aktuelle Stelle`, `Poste actuel`],
    [`July 2026 – Present`]: [`Juli 2026 – heute`, `juillet 2026 – aujourd'hui`],
    [`ESA-funded project on hyperspectral environmental monitoring.`]: [`ESA-finanziertes Projekt zum hyperspektralen Umweltmonitoring.`, `Projet financé par l'ESA sur la surveillance environnementale hyperspectrale.`],
    [`Built an end-to-end processing pipeline for airborne hyperspectral and satellite imagery.`]: [`Aufbau einer durchgängigen Verarbeitungspipeline für luftgestützte Hyperspektral- und Satellitenbilder.`, `Développement d'une chaîne de traitement complète pour l'imagerie hyperspectrale aéroportée et satellitaire.`],
    [`Validated cross-sensor and multi-resolution scaling methods against real satellite data.`]: [`Validierung sensorübergreifender und multiskaliger Skalierungsmethoden anhand realer Satellitendaten.`, `Validation de méthodes de mise à l'échelle multi-capteurs et multi-résolutions sur des données satellitaires réelles.`],
    [`Analysed how resolution and observing conditions affect vegetation trait retrieval for a mission study.`]: [`Analyse, wie Auflösung und Beobachtungsbedingungen die Ableitung von Vegetationsmerkmalen für eine Missionsstudie beeinflussen.`, `Analyse de l'influence de la résolution et des conditions d'observation sur l'estimation des traits de la végétation pour une étude de mission.`],
    [`ML Regression`]: [`ML-Regression`, `Régression ML`],
    [`Hyperspectral`]: [`Hyperspektral`, `Hyperspectral`],
    [`Multi-sensor Processing`]: [`Multisensor-Verarbeitung`, `Traitement multi-capteurs`],
    [`Scientific Writing`]: [`Wissenschaftliches Schreiben`, `Rédaction scientifique`],
    [`Research Assistant`]: [`Wissenschaftlicher Assistent`, `Assistant de recherche`],
    [`ETH Zurich`]: [`ETH Zürich`, `ETH Zurich`],
    [`Sept 2025 – Mar 2026`]: [`Sept. 2025 – März 2026`, `sept. 2025 – mars 2026`],
    [`Within the space geodesy research team.`]: [`Im Forschungsteam für Weltraumgeodäsie.`, `Au sein de l'équipe de recherche en géodésie spatiale.`],
    [`Built Python pipelines to process multi-year GNSS and ERA5 reanalysis data (NetCDF/GRIB) for atmospheric analysis.`]: [`Aufbau von Python-Pipelines zur Verarbeitung mehrjähriger GNSS- und ERA5-Reanalysedaten (NetCDF/GRIB) für atmosphärische Analysen.`, `Développement de pipelines Python pour traiter des données GNSS et de réanalyse ERA5 pluriannuelles (NetCDF/GRIB) pour l'analyse atmosphérique.`],
    [`Developed deep learning and gradient-boosting models to predict heavy rainfall from atmospheric water vapour.`]: [`Entwicklung von Deep-Learning- und Gradient-Boosting-Modellen zur Vorhersage von Starkregen aus atmosphärischem Wasserdampf.`, `Développement de modèles d'apprentissage profond et de gradient boosting pour prédire les fortes pluies à partir de la vapeur d'eau atmosphérique.`],
    [`Scaled the analysis from 1 to 12 years of data, including quality control and outlier detection.`]: [`Ausweitung der Analyse von 1 auf 12 Jahre Daten, inklusive Qualitätskontrolle und Ausreissererkennung.`, `Extension de l'analyse de 1 à 12 ans de données, avec contrôle qualité et détection des valeurs aberrantes.`],
    [`Presented the results at the Swiss Geoscience Meeting, Bern (Dec 2025).`]: [`Präsentation der Ergebnisse am Swiss Geoscience Meeting in Bern (Dez. 2025).`, `Présentation des résultats au Swiss Geoscience Meeting, à Berne (déc. 2025).`],
    [`GNSS Meteorology`]: [`GNSS-Meteorologie`, `Météorologie GNSS`],
    [`ERA5 Reanalysis`]: [`ERA5-Reanalyse`, `Réanalyse ERA5`],
    [`Time-Series Forecasting`]: [`Zeitreihenprognose`, `Prévision de séries temporelles`],
    [`Spatial Data Analyst Intern`]: [`Praktikant Spatial Data Analysis`, `Stagiaire analyste de données spatiales`],
    [`Dehradun, India`]: [`Dehradun, Indien`, `Dehradun, Inde`],
    [`Jan 2023 – Dec 2023`]: [`Jan. 2023 – Dez. 2023`, `janv. 2023 – déc. 2023`],
    [`As part of the research group.`]: [`Als Teil der Forschungsgruppe.`, `Au sein du groupe de recherche.`],
    [`Developed a U-Net model in PyTorch on Sentinel-1 data for flood detection in monsoon-affected regions.`]: [`Entwicklung eines U-Net-Modells in PyTorch auf Sentinel-1-Daten zur Hochwassererkennung in Monsungebieten.`, `Développement d'un modèle U-Net en PyTorch sur des données Sentinel-1 pour la détection des inondations dans les régions touchées par la mousson.`],
    [`Integrated four years of gridded rainfall data as additional model input channels.`]: [`Integration von vier Jahren gerasterter Niederschlagsdaten als zusätzliche Eingabekanäle des Modells.`, `Intégration de quatre années de données de précipitations maillées comme canaux d'entrée supplémentaires du modèle.`],
    [`Tuned training pipelines and hyperparameters, reaching 92% accuracy and 0.70 F1 on held-out data.`]: [
        `Optimierung der Trainingspipelines und Hyperparameter mit <strong>92 % Genauigkeit und einem F1-Wert von 0,70</strong> auf Testdaten.`,
        `Optimisation des pipelines d'entraînement et des hyperparamètres, atteignant <strong>92 % de précision et un F1 de 0,70</strong> sur des données de test.`],
    [`Deep Learning`]: [`Deep Learning`, `Apprentissage profond`],
    [`Model Evaluation`]: [`Modellevaluierung`, `Évaluation de modèles`],
    [`Concordia University`]: [`Concordia University`, `Université Concordia`],
    [`Montreal, Canada`]: [`Montreal, Kanada`, `Montréal, Canada`],
    [`June 2022 – Aug 2022`]: [`Juni 2022 – Aug. 2022`, `juin 2022 – août 2022`],
    [`MITACS Globalink Research Internship.`]: [`MITACS Globalink Research Internship.`, `Stage de recherche MITACS Globalink.`],
    [`Designed a geotextile filtration system for wetland discharge water, reducing lake nutrients by 50%.`]: [`Entwicklung eines Geotextil-Filtersystems für Abflusswasser aus Feuchtgebieten, das die Nährstoffe im See um 50 % reduzierte.`, `Conception d'un système de filtration par géotextile pour les eaux de rejet de zones humides, réduisant de 50 % les nutriments du lac.`],
    [`Conducted water quality analysis supported by remote sensing data.`]: [`Wasserqualitätsanalyse mit Unterstützung von Fernerkundungsdaten.`, `Analyse de la qualité de l'eau appuyée par des données de télédétection.`],
    [`Co-authored and presented the work at the CSCE Annual Conference 2023, Moncton, Canada.`]: [
        `Mitverfasst und präsentiert an der <strong>CSCE Annual Conference 2023</strong> in Moncton, Kanada.`,
        `Travail co-écrit et présenté à la <strong>CSCE Annual Conference 2023</strong>, à Moncton, Canada.`],
    [`Water Quality`]: [`Wasserqualität`, `Qualité de l'eau`],
    [`Remote Sensing`]: [`Fernerkundung`, `Télédétection`],
    [`Environmental Eng.`]: [`Umweltingenieurwesen`, `Génie environnemental`],
    [`Teaching Assistant`]: [`Lehrassistent`, `Assistant d'enseignement`],
    [`Vellore, India`]: [`Vellore, Indien`, `Vellore, Inde`],
    [`Sept 2021 – Jan 2023`]: [`Sept. 2021 – Jan. 2023`, `sept. 2021 – janv. 2023`],
    [`Involved in research projects and coursework during the final year of my bachelor's.`]: [`Mitarbeit an Forschungsprojekten und Lehrveranstaltungen im letzten Jahr meines Bachelorstudiums.`, `Participation à des projets de recherche et à des enseignements durant la dernière année de ma licence.`],
    [`Assisted in 3 PhD research projects involving geospatial and hydrological modelling.`]: [
        `Unterstützung bei <strong>3 Doktorandenprojekten</strong> zu Geodaten- und hydrologischer Modellierung.`,
        `Appui à <strong>3 projets de recherche doctorale</strong> en modélisation géospatiale et hydrologique.`],
    [`Mentored ~40 students in QGIS and ArcGIS, covering LULC classification and flood mapping.`]: [`Betreuung von rund 40 Studierenden in QGIS und ArcGIS, von der LULC-Klassifikation bis zur Hochwasserkartierung.`, `Encadrement d'environ 40 étudiants sur QGIS et ArcGIS, de la classification de l'occupation des sols à la cartographie des inondations.`],
    [`Developed course materials and ran workshops on satellite data processing.`]: [`Erstellung von Kursmaterialien und Durchführung von Workshops zur Verarbeitung von Satellitendaten.`, `Création de supports de cours et animation d'ateliers sur le traitement des données satellitaires.`],
    [`Teaching`]: [`Lehre`, `Enseignement`],
    [`Communication`]: [`Kommunikation`, `Communication`],
    [`Spatial Data Analysis`]: [`Räumliche Datenanalyse`, `Analyse de données spatiales`],

    // ---------- projects ----------
    [`RESEARCH PROJECTS`]: [`FORSCHUNGSPROJEKTE`, `PROJETS DE RECHERCHE`],
    [`Foundation Models`]: [`Foundation Models`, `Modèles de fondation`],
    [`Published · IEEE TGRS 2026`]: [`Veröffentlicht · IEEE TGRS 2026`, `Publié · IEEE TGRS 2026`],
    [`MapSAM2: Foundation Model for Map Segmentation`]: [`MapSAM2: Foundation Model für die Kartensegmentierung`, `MapSAM2 : modèle de fondation pour la segmentation de cartes`],
    [`ETH Zurich · Co-author`]: [`ETH Zürich · Mitautor`, `ETH Zurich · Co-auteur`],
    [`Adapted and fine-tuned the SAM2 transformer foundation model for automatic segmentation of historical maps, using video-based tile processing to share spatial context across image patches.`]: [`Anpassung und Feinabstimmung des Transformer-Foundation-Models SAM2 für die automatische Segmentierung historischer Karten, mit videobasierter Kachelverarbeitung, um räumlichen Kontext zwischen Bildausschnitten zu teilen.`, `Adaptation et ajustement fin du modèle de fondation transformer SAM2 pour la segmentation automatique de cartes historiques, avec un traitement des tuiles de type vidéo pour partager le contexte spatial entre les fragments d'image.`],
    [`SAM2 foundation model`]: [`Foundation Model SAM2`, `Modèle de fondation SAM2`],
    [`Historical maps and time series`]: [`Historische Karten und Zeitreihen`, `Cartes historiques et séries temporelles`],
    [`Video-based tile processing`]: [`Videobasierte Kachelverarbeitung`, `Traitement des tuiles de type vidéo`],
    [`View details`]: [`Details ansehen`, `Voir les détails`],
    [`Better Maps of Plant Functional Traits`]: [`Bessere Karten funktioneller Pflanzenmerkmale`, `De meilleures cartes des traits fonctionnels des plantes`],
    [`ETH Zurich · Semester Project 2`]: [`ETH Zürich · Semesterarbeit 2`, `ETH Zurich · Projet de semestre 2`],
    [`CNN, Multi-Task Learning and Mixture-of-Experts models mapping 37 plant functional traits globally, fusing 150-channel Earth observation data with GBIF and sPlot biodiversity records.`]: [`CNN-, Multi-Task-Learning- und Mixture-of-Experts-Modelle kartieren 37 funktionelle Pflanzenmerkmale weltweit und verbinden 150-kanalige Erdbeobachtungsdaten mit GBIF- und sPlot-Biodiversitätsdaten.`, `Des modèles CNN, multi-tâches et à mélange d'experts cartographient 37 traits fonctionnels des plantes à l'échelle mondiale, en combinant des données d'observation de la Terre à 150 canaux avec les relevés de biodiversité GBIF et sPlot.`],
    [`37 traits`]: [`37 Merkmale`, `37 traits`],
    [`1 km and 22 km global maps`]: [`Globale Karten mit 1 km und 22 km`, `Cartes mondiales à 1 km et 22 km`],
    [`Heavy Precipitation from GNSS Wet Delay`]: [`Starkniederschlag aus dem GNSS Wet Delay`, `Fortes précipitations à partir du retard humide GNSS`],
    [`ETH Zurich · Semester Project 1`]: [`ETH Zürich · Semesterarbeit 1`, `ETH Zurich · Projet de semestre 1`],
    [`Uses GNSS Zenith Wet Delay as a physical proxy for atmospheric water vapour to predict short-term heavy rainfall, benchmarking LSTM, XGBoost and further architectures.`]: [`Nutzt den GNSS Zenith Wet Delay als physikalischen Proxy für atmosphärischen Wasserdampf, um kurzfristigen Starkregen vorherzusagen, und vergleicht LSTM, XGBoost und weitere Architekturen.`, `Utilise le retard humide zénithal GNSS comme indicateur physique de la vapeur d'eau atmosphérique pour prévoir les fortes pluies à court terme, en comparant LSTM, XGBoost et d'autres architectures.`],
    [`LSTM best: F1 0.70`]: [`LSTM am besten: F1 0,70`, `Meilleur : LSTM, F1 0,70`],
    [`GNSS + ERA5 data`]: [`GNSS- und ERA5-Daten`, `Données GNSS + ERA5`],
    [`Hydrology`]: [`Hydrologie`, `Hydrologie`],
    [`Flood Risk Mapping with Arc-SWAT`]: [`Hochwasserrisikokartierung mit Arc-SWAT`, `Cartographie du risque d'inondation avec Arc-SWAT`],
    [`VIT Vellore · BTech thesis · Dhansiri Basin, India`]: [`VIT Vellore · BTech-Abschlussarbeit · Dhansiri-Becken, Indien`, `VIT Vellore · Mémoire de BTech · Bassin de la Dhansiri, Inde`],
    [`Hydrological modelling of the Dhansiri River watershed to map flood risk, combining a calibrated SWAT model with satellite imagery.`]: [`Hydrologische Modellierung des Einzugsgebiets des Dhansiri zur Kartierung des Hochwasserrisikos, mit einem kalibrierten SWAT-Modell und Satellitenbildern.`, `Modélisation hydrologique du bassin versant de la Dhansiri pour cartographier le risque d'inondation, en combinant un modèle SWAT calibré et des images satellites.`],
    [`NSE 0.84`]: [`NSE 0,84`, `NSE 0,84`],
    [`R² 0.90`]: [`R² 0,90`, `R² 0,90`],
    [`GIS Analysis`]: [`GIS-Analyse`, `Analyse SIG`],
    [`Groundwater Potential Zoning`]: [`Zonierung des Grundwasserpotenzials`, `Zonage du potentiel en eaux souterraines`],
    [`Ahmedabad, India`]: [`Ahmedabad, Indien`, `Ahmedabad, Inde`],
    [`Multi-criteria analysis (AHP) with satellite-derived indicators and GIS to map where groundwater potential is highest.`]: [`Multikriterienanalyse (AHP) mit satellitengestützten Indikatoren und GIS, um zu kartieren, wo das Grundwasserpotenzial am höchsten ist.`, `Analyse multicritère (AHP) avec des indicateurs satellitaires et un SIG pour cartographier les zones au plus fort potentiel en eaux souterraines.`],
    [`89% medium to high potential`]: [`89 % mittleres bis hohes Potenzial`, `89 % de potentiel moyen à élevé`],
    [`AHP + GIS`]: [`AHP + GIS`, `AHP + SIG`],

    // ---------- selected work ----------
    [`Problem`]: [`Problem`, `Problème`],
    [`Heavy-precipitation warnings need a signal that updates faster than reanalysis products can deliver.`]: [`Warnungen vor Starkniederschlägen brauchen ein Signal, das sich schneller aktualisiert, als Reanalyseprodukte es liefern können.`, `Les alertes aux fortes précipitations nécessitent un signal mis à jour plus rapidement que ne le permettent les produits de réanalyse.`],
    [`Method`]: [`Methode`, `Méthode`],
    [`Used GNSS Zenith Wet Delay as a physical proxy for atmospheric water vapour. Built Python pipelines over GNSS and ERA5 data (NetCDF/GRIB), then benchmarked LSTM, XGBoost and further architectures under identical train/test splits.`]: [`Der GNSS Zenith Wet Delay dient als physikalischer Proxy für atmosphärischen Wasserdampf. Aufbau von Python-Pipelines über GNSS- und ERA5-Daten (NetCDF/GRIB), anschliessend Vergleich von LSTM, XGBoost und weiteren Architekturen mit identischen Trainings- und Testaufteilungen.`, `Le retard humide zénithal GNSS sert d'indicateur physique de la vapeur d'eau atmosphérique. Développement de pipelines Python sur les données GNSS et ERA5 (NetCDF/GRIB), puis comparaison de LSTM, XGBoost et d'autres architectures avec des jeux d'entraînement et de test identiques.`],
    [`Result`]: [`Ergebnis`, `Résultat`],
    [`LSTM came out best at F1 0.70. Scaled from 1 to 12 years across ~5,500 European stations with quality control and outlier detection, and presented at the Swiss Geoscience Meeting, Bern (Dec 2025).`]: [
        `LSTM schnitt mit <strong>F1 0,70</strong> am besten ab. Ausgeweitet von 1 auf 12 Jahre über <strong>rund 5500 europäische Stationen</strong> mit Qualitätskontrolle und Ausreissererkennung, präsentiert am Swiss Geoscience Meeting in Bern (Dez. 2025).`,
        `Le LSTM a obtenu les meilleurs résultats avec un <strong>F1 de 0,70</strong>. Analyse étendue de 1 à 12 ans sur <strong>~5 500 stations européennes</strong>, avec contrôle qualité et détection des valeurs aberrantes, et présentée au Swiss Geoscience Meeting, à Berne (déc. 2025).`],
    [`Optical satellites are blinded by monsoon cloud cover exactly when flood maps are most needed.`]: [`Optische Satelliten sind durch die Bewölkung während des Monsuns genau dann blind, wenn Hochwasserkarten am dringendsten gebraucht werden.`, `Les satellites optiques sont aveuglés par la couverture nuageuse de la mousson, précisément quand les cartes d'inondation sont les plus nécessaires.`],
    [`Trained a U-Net in PyTorch on Sentinel-1 SAR, which sees through cloud, and added four years of gridded rainfall as extra input channels so the model had hydrological context alongside backscatter.`]: [`Training eines U-Net in PyTorch auf Sentinel-1-SAR, das durch Wolken hindurchsieht, ergänzt um vier Jahre gerasterter Niederschlagsdaten als zusätzliche Eingabekanäle, damit das Modell neben der Rückstreuung auch hydrologischen Kontext hat.`, `Entraînement d'un U-Net en PyTorch sur des données SAR Sentinel-1, qui voient à travers les nuages, avec quatre années de précipitations maillées en canaux d'entrée supplémentaires pour donner au modèle un contexte hydrologique en plus de la rétrodiffusion.`],
    [`92% accuracy and 0.70 F1 on held-out data after tuning the training pipeline and hyperparameters — work carried out at IIRS, ISRO.`]: [
        `<strong>92 % Genauigkeit und F1 0,70</strong> auf Testdaten nach Optimierung der Trainingspipeline und der Hyperparameter – durchgeführt am IIRS, ISRO.`,
        `<strong>92 % de précision et un F1 de 0,70</strong> sur des données de test après optimisation de la chaîne d'entraînement et des hyperparamètres — travail réalisé à l'IIRS, ISRO.`],
    [`Plant functional traits drive ecosystem models, but ground observations are sparse and unevenly distributed.`]: [`Funktionelle Pflanzenmerkmale steuern Ökosystemmodelle, doch Bodenbeobachtungen sind spärlich und ungleich verteilt.`, `Les traits fonctionnels des plantes alimentent les modèles d'écosystèmes, mais les observations au sol sont rares et inégalement réparties.`],
    [`Extended the planttraits.earth framework with CNN, Multi-Task Learning and Mixture-of-Experts models, fusing 150-channel Earth observation data with GBIF and sPlot biodiversity records.`]: [`Erweiterung des planttraits.earth-Frameworks um CNN-, Multi-Task-Learning- und Mixture-of-Experts-Modelle, die 150-kanalige Erdbeobachtungsdaten mit GBIF- und sPlot-Biodiversitätsdaten verbinden.`, `Extension du cadre planttraits.earth avec des modèles CNN, multi-tâches et à mélange d'experts, combinant des données d'observation de la Terre à 150 canaux avec les relevés de biodiversité GBIF et sPlot.`],
    [`Global trait maps generated and evaluated at 1 km and 22 km resolutions, covering 37 traits.`]: [
        `Globale Merkmalskarten mit <strong>1 km und 22 km</strong> Auflösung erstellt und evaluiert, für <strong>37 Merkmale</strong>.`,
        `Cartes mondiales des traits générées et évaluées à des résolutions de <strong>1 km et 22 km</strong>, couvrant <strong>37 traits</strong>.`],
    [`Multi-Task Learning`]: [`Multi-Task Learning`, `Apprentissage multi-tâches`],
    [`Mixture-of-Experts`]: [`Mixture-of-Experts`, `Mélange d'experts`],

    // ---------- publications ----------
    [`RESEARCH PUBLICATIONS`]: [`PUBLIKATIONEN`, `PUBLICATIONS`],
    [`Read Paper`]: [`Artikel lesen`, `Lire l'article`],
    [`First author`]: [`Erstautor`, `Premier auteur`],
    [`CSCE Annual Conference 2023 • Moncton, Canada`]: [`CSCE Annual Conference 2023 • Moncton, Kanada`, `CSCE Annual Conference 2023 • Moncton, Canada`],

    // ---------- education ----------
    [`EDUCATION`]: [`AUSBILDUNG`, `FORMATION`],
    [`MSc in Geomatics Engineering · GPA 5.33/6.0`]: [`MSc in Geomatik · Notenschnitt 5,33/6,0`, `Master en géomatique · Moyenne 5,33/6,0`],
    [`Sept 2024 – Mar 2027`]: [`Sept. 2024 – März 2027`, `sept. 2024 – mars 2027`],
    [`GPA 5.33/6.0, specialising in Earth observation and geospatial machine learning`]: [
        `<strong>Notenschnitt 5,33/6,0</strong>, Schwerpunkt Erdbeobachtung und maschinelles Lernen für Geodaten`,
        `<strong>Moyenne 5,33/6,0</strong>, spécialisation en observation de la Terre et apprentissage automatique géospatial`],
    [`Semester Project 1: Detection of Heavy Precipitation using GNSS Zenith Wet Delay`]: [
        `<strong>Semesterarbeit 1:</strong> Erkennung von Starkniederschlägen mit dem GNSS Zenith Wet Delay`,
        `<strong>Projet de semestre 1 :</strong> Détection des fortes précipitations à l'aide du retard humide zénithal GNSS`],
    [`Semester Project 2: Better maps of plant functional traits – towards planttraits.earth v2`]: [
        `<strong>Semesterarbeit 2:</strong> Bessere Karten funktioneller Pflanzenmerkmale – auf dem Weg zu planttraits.earth v2`,
        `<strong>Projet de semestre 2 :</strong> De meilleures cartes des traits fonctionnels des plantes – vers planttraits.earth v2`],
    [`Coursework: Deep Learning, Introduction to Machine Learning, Multivariate Statistics and Machine Learning, Space Geodesy, Geospatial Research Methods`]: [`Kurse: Deep Learning, Introduction to Machine Learning, Multivariate Statistics and Machine Learning, Space Geodesy, Geospatial Research Methods`, `Cours : Deep Learning, Introduction to Machine Learning, Multivariate Statistics and Machine Learning, Space Geodesy, Geospatial Research Methods`],
    [`Space Geodesy`]: [`Weltraumgeodäsie`, `Géodésie spatiale`],
    [`BTech in Civil Engineering · CGPA 9.33/10.0`]: [`BTech in Bauingenieurwesen · CGPA 9,33/10,0`, `BTech en génie civil · CGPA 9,33/10,0`],
    [`July 2019 – May 2023`]: [`Juli 2019 – Mai 2023`, `juillet 2019 – mai 2023`],
    [`CGPA 9.33/10.0 — ranked 2nd of ~150 students, and named Best Outgoing Student`]: [
        `<strong>CGPA 9,33/10,0 – Rang 2 von rund 150 Studierenden</strong> und als bester Absolvent ausgezeichnet`,
        `<strong>CGPA 9,33/10,0 — 2e sur environ 150 étudiants</strong>, et distingué meilleur diplômé`],
    [`Thesis: Flood Risk Analysis using Arc-SWAT in the Dhansiri River Watershed, India`]: [
        `<strong>Abschlussarbeit:</strong> Hochwasserrisikoanalyse mit Arc-SWAT im Einzugsgebiet des Dhansiri, Indien`,
        `<strong>Mémoire :</strong> Analyse du risque d'inondation avec Arc-SWAT dans le bassin versant de la Dhansiri, Inde`],
    [`Merit-based scholarship for 3 consecutive years for academic excellence`]: [`Leistungsstipendium für 3 aufeinanderfolgende Jahre für herausragende Studienleistungen`, `Bourse au mérite pendant 3 années consécutives pour l'excellence académique`],
    [`Coursework: Hydrology, GIS and Remote Sensing, Environmental Engineering`]: [`Kurse: Hydrologie, GIS und Fernerkundung, Umweltingenieurwesen`, `Cours : hydrologie, SIG et télédétection, génie de l'environnement`],
    [`GIS & Remote Sensing`]: [`GIS & Fernerkundung`, `SIG et télédétection`],

    // ---------- globe section (page text) ----------
    [`WHERE I'VE WORKED`]: [`WO ICH GEARBEITET HABE`, `OÙ J'AI TRAVAILLÉ`],
    [`Drag to spin, pinch or use the buttons to zoom. Select a place, on the globe or in the list, to see what I did there.`]: [`Zum Drehen ziehen, zum Zoomen die Finger spreizen oder die Schaltflächen nutzen. Wählen Sie einen Ort auf dem Globus oder in der Liste, um zu sehen, was ich dort gemacht habe.`, `Faites glisser pour faire tourner le globe, pincez ou utilisez les boutons pour zoomer. Sélectionnez un lieu, sur le globe ou dans la liste, pour voir ce que j'y ai fait.`],
    [`Loading globe…`]: [`Globus wird geladen…`, `Chargement du globe…`],

    // ---------- achievements ----------
    [`MITACS Globalink Research Scholar`]: [`MITACS Globalink Research Scholar`, `Boursier de recherche MITACS Globalink`],
    [`Awarded prestigious MITACS scholarship for international research internship at Concordia University, Canada, selected among top candidates nationwide.`]: [`Mit dem renommierten MITACS-Stipendium für ein internationales Forschungspraktikum an der Concordia University, Kanada, ausgezeichnet – ausgewählt unter den besten Bewerbenden landesweit.`, `Lauréat de la prestigieuse bourse MITACS pour un stage de recherche international à l'Université Concordia, au Canada, sélectionné parmi les meilleurs candidats du pays.`],
    [`View Certificate`]: [`Zertifikat ansehen`, `Voir le certificat`],
    [`Road Safety Hackathon Winner`]: [`Gewinner des Road Safety Hackathons`, `Lauréat du hackathon sur la sécurité routière`],
    [`1st place in national competition for "Implementable Local Action Plan for Road Safety". Proposal was considered for implementation by IIT Madras.`]: [`1. Platz in einem nationalen Wettbewerb für einen „Implementable Local Action Plan for Road Safety“. Der Vorschlag wurde vom IIT Madras für die Umsetzung in Betracht gezogen.`, `1re place d'un concours national pour un « Implementable Local Action Plan for Road Safety ». La proposition a été envisagée pour une mise en œuvre par l'IIT Madras.`],
    [`University Rank Holder`]: [`Rangauszeichnung der Universität`, `Distinction de rang universitaire`],
    [`Secured 2nd rank in Civil Engineering department with CGPA of 9.33/10.0, recognized for academic excellence among 150 students.`]: [`Rang 2 im Studiengang Bauingenieurwesen mit einem CGPA von 9,33/10,0, ausgezeichnet für herausragende Leistungen unter 150 Studierenden.`, `2e rang du département de génie civil avec un CGPA de 9,33/10,0, distingué pour l'excellence académique parmi 150 étudiants.`],
    [`Merit Scholarship (3 Years)`]: [`Leistungsstipendium (3 Jahre)`, `Bourse au mérite (3 ans)`],
    [`Awarded university merit scholarship for three consecutive years recognizing consistent academic performance in top 5% of class.`]: [`Universitäres Leistungsstipendium für drei aufeinanderfolgende Jahre für konstant hervorragende Leistungen (Top 5 % des Jahrgangs).`, `Bourse au mérite universitaire pendant trois années consécutives, récompensant des résultats constants parmi les 5 % meilleurs de la promotion.`],
    [`View Certificates`]: [`Zertifikate ansehen`, `Voir les certificats`],
    [`Best Outgoing Student`]: [`Bester Absolvent`, `Meilleur diplômé`],
    [`Named Best Outgoing Student of the Civil Engineering department, recognising academic performance, research output and contribution to the university community.`]: [`Als bester Absolvent (Best Outgoing Student) des Studiengangs Bauingenieurwesen ausgezeichnet, in Anerkennung von Studienleistungen, Forschungsergebnissen und Engagement für die Universität.`, `Distingué meilleur diplômé (Best Outgoing Student) du département de génie civil, pour ses résultats académiques, sa production scientifique et sa contribution à la vie universitaire.`],
    [`All India Course Topper`]: [`Landesweit Bester (All India Course Topper)`, `Premier au niveau national (All India Course Topper)`],
    [`Nationwide`]: [`Landesweit`, `Au niveau national`],
    [`Ranked first nationally on a certified course, awarded an All India Course Topper certificate.`]: [`Landesweit Erster in einem zertifizierten Kurs, ausgezeichnet mit dem Zertifikat All India Course Topper.`, `Premier au niveau national d'une formation certifiante, récompensé par le certificat All India Course Topper.`],
    [`Selected among 10 students nationwide for educational tour to ATAL Tunnel, sponsored by Government of India to study advanced construction techniques.`]: [`Als einer von 10 Studierenden landesweit für eine von der indischen Regierung geförderte Studienreise zum Atal-Tunnel ausgewählt, um moderne Bautechniken kennenzulernen.`, `Sélectionné parmi 10 étudiants du pays pour un voyage d'études au tunnel Atal, financé par le gouvernement indien, afin d'étudier des techniques de construction avancées.`],

    // ---------- speaking ----------
    [`Bern, Switzerland · Dec 2025`]: [`Bern, Schweiz · Dez. 2025`, `Berne, Suisse · déc. 2025`],
    [`Presented results on detecting heavy precipitation from GNSS Zenith Wet Delay, carried out with the ETH Zurich Space Geodesy group.`]: [`Präsentation von Ergebnissen zur Erkennung von Starkniederschlägen aus dem GNSS Zenith Wet Delay, entstanden in der Gruppe für Weltraumgeodäsie der ETH Zürich.`, `Présentation de résultats sur la détection des fortes précipitations à partir du retard humide zénithal GNSS, réalisés avec le groupe de géodésie spatiale de l'ETH Zurich.`],
    [`Moncton, Canada · 2023`]: [`Moncton, Kanada · 2023`, `Moncton, Canada · 2023`],
    [`Co-authored and presented work on wetland discharge water filtration of a mesotrophic lake, from the MITACS internship at Concordia University.`]: [`Mitverfasst und präsentiert: Arbeit zur Filtration von Feuchtgebietsabflüssen in einen mesotrophen See, aus dem MITACS-Praktikum an der Concordia University.`, `Travail co-écrit et présenté sur la filtration des eaux de rejet de zones humides d'un lac mésotrophe, issu du stage MITACS à l'Université Concordia.`],
    [`Guest Speaker - Fresher Induction`]: [`Gastredner – Einführung für Erstsemester`, `Intervenant invité – accueil des nouveaux étudiants`],
    [`Invited to share my academic journey and research experiences with incoming civil engineering students during orientation program.`]: [`Eingeladen, im Rahmen der Orientierungswoche meinen akademischen Werdegang und meine Forschungserfahrungen mit neuen Bauingenieur-Studierenden zu teilen.`, `Invité à partager mon parcours académique et mon expérience de recherche avec les nouveaux étudiants en génie civil lors de la semaine d'intégration.`],
    [`Roorkee, India · Mar 2022`]: [`Roorkee, Indien · März 2022`, `Roorkee, Inde · mars 2022`],
    [`Presented research on flood-prone zone identification in Bihar using HEC-RAS modelling and satellite data analysis.`]: [`Präsentation von Forschung zur Identifikation hochwassergefährdeter Gebiete in Bihar mit HEC-RAS-Modellierung und Satellitendatenanalyse.`, `Présentation de travaux sur l'identification des zones inondables au Bihar grâce à la modélisation HEC-RAS et à l'analyse de données satellitaires.`],

    // ---------- beyond the work ----------
    [`BEYOND THE WORK`]: [`ÜBER DIE ARBEIT HINAUS`, `AU-DELÀ DU TRAVAIL`],
    [`Languages`]: [`Sprachen`, `Langues`],
    [`Native`]: [`Muttersprache`, `Langue maternelle`],
    [`English`]: [`Englisch`, `Anglais`],
    [`German`]: [`Deutsch`, `Allemand`],
    [`A2 · learning`]: [`A2 · am Lernen`, `A2 · en apprentissage`],
    [`Positions & Volunteering`]: [`Ämter & Engagement`, `Responsabilités et bénévolat`],
    [`Academic Head, Educational Startup`]: [`Akademischer Leiter, Bildungs-Startup`, `Responsable pédagogique, start-up éducative`],
    [`Mar 2020 – Mar 2022`]: [`März 2020 – März 2022`, `mars 2020 – mars 2022`],
    [`Led the academic side of an early-stage education startup, shaping course content and teaching standards.`]: [`Leitung des akademischen Bereichs eines jungen Bildungs-Startups, einschliesslich Kursinhalten und Lehrstandards.`, `Direction du volet pédagogique d'une jeune start-up éducative : contenus de cours et exigences d'enseignement.`],
    [`Core Member, ASCE University Chapter`]: [`Kernmitglied, ASCE-Hochschulgruppe`, `Membre du bureau, section universitaire de l'ASCE`],
    [`Sept 2019 – Dec 2022`]: [`Sept. 2019 – Dez. 2022`, `sept. 2019 – déc. 2022`],
    [`Core committee member of the American Society of Civil Engineers (ASCE) student chapter, organising technical events and student activities.`]: [`Mitglied im Kernteam der studentischen Hochschulgruppe der American Society of Civil Engineers (ASCE), Organisation von Fachveranstaltungen und studentischen Aktivitäten.`, `Membre du bureau de la section étudiante de l'American Society of Civil Engineers (ASCE), organisation d'événements techniques et d'activités étudiantes.`],
    [`Interests`]: [`Interessen`, `Centres d'intérêt`],
    [`Hindi Poetry`]: [`Hindi-Poesie`, `Poésie hindi`],
    [`Reading & writing`]: [`Lesen & Schreiben`, `Lecture et écriture`],
    [`Chess`]: [`Schach`, `Échecs`],
    [`Long-time player`]: [`Langjähriger Spieler`, `Joueur de longue date`],
    [`Cooking`]: [`Kochen`, `Cuisine`],
    [`Indian fusion`]: [`Indische Fusionsküche`, `Cuisine fusion indienne`],
    [`Writing`]: [`Schreiben`, `Écriture`],

    // ---------- contact, footer ----------
    [`GET IN TOUCH`]: [`KONTAKT`, `CONTACT`],
    [`Passionate about geospatial technologies and climate solutions. Open to research collaborations and impactful projects.`]: [`Begeistert von Geodatentechnologien und Klimalösungen. Offen für Forschungskooperationen und Projekte mit Wirkung.`, `Passionné par les technologies géospatiales et les solutions climatiques. Ouvert aux collaborations de recherche et aux projets à impact.`],
    [`Email Me`]: [`E-Mail senden`, `M'écrire`],
    [`Call Me`]: [`Anrufen`, `M'appeler`],
    [`Share Portfolio`]: [`Portfolio teilen`, `Partager le portfolio`],
    [`Dev Shree Saini | Earth Observation & Geospatial Machine Learning`]: [`Dev Shree Saini | Erdbeobachtung & maschinelles Lernen für Geodaten`, `Dev Shree Saini | Observation de la Terre et apprentissage automatique géospatial`],
    [`Last updated September 2026`]: [`Zuletzt aktualisiert: September 2026`, `Dernière mise à jour : septembre 2026`],
    [`Built with and | © 2026 | All systems operational`]: [
        `Erstellt mit <i class="fas fa-heart text-[--accent-primary]"></i> und <i class="fas fa-code text-[--accent-secondary]"></i> | © 2026 | Alle Systeme betriebsbereit`,
        `Conçu avec <i class="fas fa-heart text-[--accent-primary]"></i> et <i class="fas fa-code text-[--accent-secondary]"></i> | © 2026 | Tous les systèmes sont opérationnels`],
    [`✅ Link copied to clipboard!`]: [`✅ Link in die Zwischenablage kopiert!`, `✅ Lien copié dans le presse-papiers !`],

    // ---------- project pop-ups (js/main.js) ----------
    [`Project Details`]: [`Projektdetails`, `Détails du projet`],
    [`View Code`]: [`Code ansehen`, `Voir le code`],
    [`View Report`]: [`Bericht ansehen`, `Voir le rapport`],
    [`Detection of Heavy Precipitation using GNSS Zenith Wet Delay`]: [`Erkennung von Starkniederschlägen mit dem GNSS Zenith Wet Delay`, `Détection des fortes précipitations à l'aide du retard humide zénithal GNSS`],
    [`ETH Zurich • Semester Project 1`]: [`ETH Zürich • Semesterarbeit 1`, `ETH Zurich • Projet de semestre 1`],
    [`Used GNSS Zenith Wet Delay as a physical proxy for atmospheric water vapour to predict short-term heavy rainfall, benchmarking several architectures under identical train/test splits.`]: [`Nutzung des GNSS Zenith Wet Delay als physikalischer Proxy für atmosphärischen Wasserdampf zur Vorhersage von kurzfristigem Starkregen, mit einem Vergleich mehrerer Architekturen bei identischen Trainings- und Testaufteilungen.`, `Utilisation du retard humide zénithal GNSS comme indicateur physique de la vapeur d'eau atmosphérique pour prévoir les fortes pluies à court terme, en comparant plusieurs architectures avec des jeux d'entraînement et de test identiques.`],
    [`Processed GNSS and ERA5 reanalysis data (NetCDF/GRIB) from ~3,200 European stations`]: [`Verarbeitung von GNSS- und ERA5-Reanalysedaten (NetCDF/GRIB) von rund 3200 europäischen Stationen`, `Traitement des données GNSS et de réanalyse ERA5 (NetCDF/GRIB) de ~3 200 stations européennes`],
    [`Benchmarked LSTM, XGBoost and further architectures under identical train/test splits`]: [`Vergleich von LSTM, XGBoost und weiteren Architekturen mit identischen Trainings- und Testaufteilungen`, `Comparaison de LSTM, XGBoost et d'autres architectures avec des jeux d'entraînement et de test identiques`],
    [`LSTM performed best, reaching the highest F1 score (0.70) of all tested architectures`]: [`LSTM schnitt am besten ab und erreichte den höchsten F1-Wert (0,70) aller getesteten Architekturen`, `Le LSTM a obtenu les meilleurs résultats, avec le F1 le plus élevé (0,70) parmi toutes les architectures testées`],
    [`Extended in the Space Geodesy RA role to 12 years across ~5,500 stations`]: [`In der Assistenzstelle in der Weltraumgeodäsie auf 12 Jahre und rund 5500 Stationen ausgeweitet`, `Étendu à 12 ans et ~5 500 stations dans le cadre du poste d'assistant en géodésie spatiale`],
    [`Presented at the Swiss Geoscience Meeting, Bern (Dec 2025)`]: [`Präsentiert am Swiss Geoscience Meeting in Bern (Dez. 2025)`, `Présenté au Swiss Geoscience Meeting, à Berne (déc. 2025)`],
    [`ETH Zurich • IEEE TGRS, 2026`]: [`ETH Zürich • IEEE TGRS, 2026`, `ETH Zurich • IEEE TGRS, 2026`],
    [`Adapted the SAM2 transformer foundation model for automatic segmentation of historical map images and time series, enabling scalable extraction of cartographic information. Published in IEEE Transactions on Geoscience and Remote Sensing.`]: [`Anpassung des Transformer-Foundation-Models SAM2 für die automatische Segmentierung historischer Kartenbilder und Zeitreihen, um kartografische Informationen skalierbar zu extrahieren. Veröffentlicht in IEEE Transactions on Geoscience and Remote Sensing.`, `Adaptation du modèle de fondation transformer SAM2 à la segmentation automatique d'images et de séries temporelles de cartes historiques, pour une extraction à grande échelle d'informations cartographiques. Publié dans IEEE Transactions on Geoscience and Remote Sensing.`],
    [`Adapted and fine-tuned the SAM2 foundation model for historical map segmentation`]: [`Anpassung und Feinabstimmung des Foundation Models SAM2 für die Segmentierung historischer Karten`, `Adaptation et ajustement fin du modèle de fondation SAM2 pour la segmentation de cartes historiques`],
    [`Implemented video-based tile processing to share spatial context across image patches`]: [`Umsetzung einer videobasierten Kachelverarbeitung, um räumlichen Kontext zwischen Bildausschnitten zu teilen`, `Mise en place d'un traitement des tuiles de type vidéo pour partager le contexte spatial entre les fragments d'image`],
    [`Evaluated on both single map images and map time series`]: [`Evaluierung sowohl an einzelnen Kartenbildern als auch an Kartenzeitreihen`, `Évaluation sur des images de cartes isolées et sur des séries temporelles de cartes`],
    [`Co-authored publication in IEEE Transactions on Geoscience and Remote Sensing (2026)`]: [`Mitverfasste Publikation in IEEE Transactions on Geoscience and Remote Sensing (2026)`, `Publication co-écrite dans IEEE Transactions on Geoscience and Remote Sensing (2026)`],
    [`Transformers`]: [`Transformer`, `Transformers`],
    [`Segmentation`]: [`Segmentierung`, `Segmentation`],
    [`VIT Vellore • BTech thesis • Dhansiri River Basin, India`]: [`VIT Vellore • BTech-Abschlussarbeit • Einzugsgebiet des Dhansiri, Indien`, `VIT Vellore • Mémoire de BTech • Bassin de la Dhansiri, Inde`],
    [`Conducted comprehensive flood risk analysis using SWAT hydrological model with NSE: 0.84 and R²: 0.90. The project integrated satellite imagery and hydrological modeling to identify high-risk zones and recommend mitigation strategies.`]: [`Umfassende Hochwasserrisikoanalyse mit dem hydrologischen Modell SWAT (NSE: 0,84, R²: 0,90). Das Projekt verband Satellitenbilder und hydrologische Modellierung, um Hochrisikogebiete zu identifizieren und Schutzmassnahmen zu empfehlen.`, `Analyse complète du risque d'inondation avec le modèle hydrologique SWAT (NSE : 0,84, R² : 0,90). Le projet a combiné images satellites et modélisation hydrologique pour identifier les zones à haut risque et recommander des mesures d'atténuation.`],
    [`Calibrated SWAT model with NSE: 0.84 and R²: 0.90`]: [`Kalibrierung des SWAT-Modells mit NSE: 0,84 und R²: 0,90`, `Calage du modèle SWAT avec NSE : 0,84 et R² : 0,90`],
    [`Processed Sentinel-2 imagery for land use classification`]: [`Verarbeitung von Sentinel-2-Bildern zur Landnutzungsklassifikation`, `Traitement d'images Sentinel-2 pour la classification de l'occupation des sols`],
    [`Developed flood risk maps for the Dhansiri River Basin`]: [`Erstellung von Hochwasserrisikokarten für das Einzugsgebiet des Dhansiri`, `Élaboration de cartes du risque d'inondation pour le bassin de la Dhansiri`],
    [`Recommended mitigation strategies for high-risk areas`]: [`Empfehlung von Schutzmassnahmen für Hochrisikogebiete`, `Recommandation de mesures d'atténuation pour les zones à haut risque`],
    [`AHP analysis using satellite data and GIS to identify 89% medium to high potential groundwater zones. The study helped local authorities in sustainable water resource management and planning.`]: [`AHP-Analyse mit Satellitendaten und GIS, die 89 % der Fläche als Zonen mit mittlerem bis hohem Grundwasserpotenzial auswies. Die Studie unterstützte lokale Behörden bei der nachhaltigen Bewirtschaftung und Planung von Wasserressourcen.`, `Analyse AHP à partir de données satellitaires et d'un SIG, identifiant 89 % de zones à potentiel moyen à élevé en eaux souterraines. L'étude a aidé les autorités locales dans la gestion et la planification durables des ressources en eau.`],
    [`Analyzed satellite-derived groundwater indicators`]: [`Analyse satellitengestützter Grundwasserindikatoren`, `Analyse d'indicateurs d'eaux souterraines issus de données satellitaires`],
    [`Applied Analytical Hierarchy Process (AHP) for zoning`]: [`Anwendung des Analytic Hierarchy Process (AHP) zur Zonierung`, `Application de la méthode AHP (processus de hiérarchie analytique) pour le zonage`],
    [`Identified 89% medium to high potential zones`]: [`Identifikation von 89 % Zonen mit mittlerem bis hohem Potenzial`, `Identification de 89 % de zones à potentiel moyen à élevé`],
    [`Validated results with field measurements`]: [`Validierung der Ergebnisse mit Feldmessungen`, `Validation des résultats par des mesures de terrain`],
    [`GIS`]: [`GIS`, `SIG`],
    [`Water Resources`]: [`Wasserressourcen`, `Ressources en eau`],
    [`ETH Zurich • Semester Project 2`]: [`ETH Zürich • Semesterarbeit 2`, `ETH Zurich • Projet de semestre 2`],
    [`Extended the planttraits.earth framework for global mapping of 37 plant functional traits, combining large-scale Earth observation data with biodiversity records.`]: [`Erweiterung des planttraits.earth-Frameworks für die globale Kartierung von 37 funktionellen Pflanzenmerkmalen, durch Verbindung grossräumiger Erdbeobachtungsdaten mit Biodiversitätsdaten.`, `Extension du cadre planttraits.earth pour la cartographie mondiale de 37 traits fonctionnels des plantes, en combinant des données d'observation de la Terre à grande échelle et des relevés de biodiversité.`],
    [`Extended the planttraits.earth framework for global mapping of 37 plant functional traits`]: [`Erweiterung des planttraits.earth-Frameworks für die globale Kartierung von 37 funktionellen Pflanzenmerkmalen`, `Extension du cadre planttraits.earth pour la cartographie mondiale de 37 traits fonctionnels des plantes`],
    [`Developed CNN, Multi-Task Learning and Mixture-of-Experts models for multi-trait prediction`]: [`Entwicklung von CNN-, Multi-Task-Learning- und Mixture-of-Experts-Modellen zur Vorhersage mehrerer Merkmale`, `Développement de modèles CNN, multi-tâches et à mélange d'experts pour la prédiction de plusieurs traits`],
    [`Integrated 150-channel Earth Observation data with GBIF and sPlot biodiversity records`]: [`Integration von 150-kanaligen Erdbeobachtungsdaten mit GBIF- und sPlot-Biodiversitätsdaten`, `Intégration de données d'observation de la Terre à 150 canaux avec les relevés de biodiversité GBIF et sPlot`],
    [`Generated and evaluated global trait maps at 1 km and 22 km resolutions`]: [`Erstellung und Evaluierung globaler Merkmalskarten mit 1 km und 22 km Auflösung`, `Production et évaluation de cartes mondiales des traits à 1 km et 22 km de résolution`],

    // ---------- career globe (js/globe.js) ----------
    [`Studied & worked`]: [`Studium & Arbeit`, `Études et travail`],
    [`Study areas`]: [`Untersuchungsgebiete`, `Zones d'étude`],
    [`Conferences`]: [`Konferenzen`, `Conférences`],
    [`Select a place, on the globe or in the list, to see what I did there.`]: [`Wählen Sie einen Ort auf dem Globus oder in der Liste, um zu sehen, was ich dort gemacht habe.`, `Sélectionnez un lieu, sur le globe ou dans la liste, pour voir ce que j'y ai fait.`],
    [`See details`]: [`Details ansehen`, `Voir les détails`],
    [`The 3D globe could not load. The list still works.`]: [`Der 3D-Globus konnte nicht geladen werden. Die Liste funktioniert weiterhin.`, `Le globe 3D n'a pas pu se charger. La liste fonctionne toujours.`],
    [`Dhansiri River Basin, Assam`]: [`Einzugsgebiet des Dhansiri, Assam`, `Bassin de la Dhansiri, Assam`],
    [`Chilika Lake, Odisha`]: [`Chilika-See, Odisha`, `Lac Chilika, Odisha`],
    [`Kallanai Dam, Cauvery Basin`]: [`Kallanai-Damm, Cauvery-Becken`, `Barrage de Kallanai, bassin de la Cauvery`],
    [`Roorkee, India`]: [`Roorkee, Indien`, `Roorkee, Inde`],
    [`Moncton, Canada`]: [`Moncton, Kanada`, `Moncton, Canada`],
    [`Bern, Switzerland`]: [`Bern, Schweiz`, `Berne, Suisse`],
    [`2024 – now`]: [`2024 – heute`, `2024 – aujourd'hui`],
    [`ETH Zurich · University of Zurich`]: [`ETH Zürich · Universität Zürich`, `ETH Zurich · Université de Zurich`],
    [`Study area`]: [`Untersuchungsgebiet`, `Zone d'étude`],
    [`BTech Civil Engineering — CGPA 9.33, ranked 2nd of ~150`]: [`BTech Bauingenieurwesen — CGPA 9,33, Rang 2 von rund 150`, `BTech génie civil — CGPA 9,33, 2e sur environ 150`],
    [`Teaching Assistant on 3 PhD research projects`]: [`Lehrassistent in 3 Doktorandenprojekten`, `Assistant d'enseignement sur 3 projets de doctorat`],
    [`MITACS Globalink Research Intern`]: [`MITACS Globalink Research Intern`, `Stagiaire de recherche MITACS Globalink`],
    [`Wetland discharge filtration — CSCE 2023 paper`]: [`Filtration von Feuchtgebietsabflüssen — Beitrag CSCE 2023`, `Filtration des rejets de zones humides — article CSCE 2023`],
    [`Sentinel-1 U-Net flood detection — 92% accuracy, 0.70 F1`]: [`Hochwassererkennung mit U-Net auf Sentinel-1 — 92 % Genauigkeit, F1 0,70`, `Détection des inondations par U-Net sur Sentinel-1 — 92 % de précision, F1 0,70`],
    [`MSc Geomatics, ETH Zurich — GPA 5.33/6.0`]: [`MSc Geomatik, ETH Zürich — Notenschnitt 5,33/6,0`, `Master en géomatique, ETH Zurich — moyenne 5,33/6,0`],
    [`Research Assistant, Space Geodesy — GNSS heavy-rainfall prediction`]: [`Wissenschaftlicher Assistent, Weltraumgeodäsie — Starkregenvorhersage mit GNSS`, `Assistant de recherche, géodésie spatiale — prévision des fortes pluies par GNSS`],
    [`Research Intern, Remote Sensing Laboratories — ESA project`]: [`Forschungspraktikant, Remote Sensing Laboratories — ESA-Projekt`, `Stagiaire de recherche, Remote Sensing Laboratories — projet ESA`],
    [`BTech thesis: flood risk analysis with Arc-SWAT`]: [`BTech-Abschlussarbeit: Hochwasserrisikoanalyse mit Arc-SWAT`, `Mémoire de BTech : analyse du risque d'inondation avec Arc-SWAT`],
    [`Land use/cover and ecosystem services — first-author paper, Estuaries and Coasts`]: [`Landnutzung und Ökosystemleistungen — Artikel als Erstautor, Estuaries and Coasts`, `Occupation des sols et services écosystémiques — article en premier auteur, Estuaries and Coasts`],
    [`Groundwater potential zoning with AHP and GIS`]: [`Zonierung des Grundwasserpotenzials mit AHP und GIS`, `Zonage du potentiel en eaux souterraines avec AHP et SIG`],
    [`Short-duration precipitation and water resources in the Cauvery Basin — Scientific Reports (2023)`]: [`Kurzzeitige Niederschläge und Wasserressourcen im Cauvery-Becken — Scientific Reports (2023)`, `Précipitations de courte durée et ressources en eau dans le bassin de la Cauvery — Scientific Reports (2023)`],
    [`Presented flood-prone zone mapping in Bihar with HEC-RAS`]: [`Vortrag zur Kartierung hochwassergefährdeter Gebiete in Bihar mit HEC-RAS`, `Présentation sur la cartographie des zones inondables au Bihar avec HEC-RAS`],
    [`Presented wetland discharge filtration research from the MITACS internship`]: [`Vortrag zur Filtration von Feuchtgebietsabflüssen aus dem MITACS-Praktikum`, `Présentation des travaux sur la filtration des rejets de zones humides issus du stage MITACS`],
    [`Presented heavy-precipitation detection from GNSS Zenith Wet Delay`]: [`Vortrag zur Erkennung von Starkniederschlägen aus dem GNSS Zenith Wet Delay`, `Présentation sur la détection des fortes précipitations à partir du retard humide zénithal GNSS`],
    // ---------- SAR flood project + figure credit (merge pass) ----------
    [`Flood Detection from Sentinel-1 SAR`]: [`Hochwassererkennung mit Sentinel-1-SAR`, `Détection des inondations par SAR Sentinel-1`],
    [`A U-Net in PyTorch on Sentinel-1 radar, which sees through monsoon cloud, with four years of gridded rainfall added as extra input channels.`]: [`Ein U-Net in PyTorch auf Sentinel-1-Radardaten, die durch Monsunwolken hindurchsehen, ergänzt um vier Jahre gerasterter Niederschlagsdaten als zusätzliche Eingabekanäle.`, `Un U-Net en PyTorch sur des données radar Sentinel-1, qui voient à travers les nuages de la mousson, complété par quatre années de précipitations maillées comme canaux d'entrée supplémentaires.`],
    [`92% accuracy`]: [`92 % Genauigkeit`, `92 % de précision`],
    [`F1 0.70`]: [`F1 0,70`, `F1 0,70`],
    [`IIRS, ISRO • Spatial Data Analyst Internship, 2023`]: [`IIRS, ISRO • Praktikum Spatial Data Analysis, 2023`, `IIRS, ISRO • Stage d'analyste de données spatiales, 2023`],
    [`Deep learning flood mapping for monsoon-affected regions, using radar imagery that sees through the cloud cover that blinds optical satellites.`]: [`Hochwasserkartierung mit Deep Learning für Monsungebiete, auf Basis von Radarbildern, die durch die Bewölkung hindurchsehen, an der optische Satelliten scheitern.`, `Cartographie des inondations par apprentissage profond dans les régions de mousson, à partir d'images radar qui traversent la couverture nuageuse qui aveugle les satellites optiques.`],
    [`Image: NASA Visible Earth (Blue Marble)`]: [`Bild: NASA Visible Earth (Blue Marble)`, `Image : NASA Visible Earth (Blue Marble)`],
    // ---------- layout pass ----------
    [`AWARDS & TALKS`]: [`AUSZEICHNUNGEN & VORTRÄGE`, `DISTINCTIONS ET INTERVENTIONS`],
    [`Awards`]: [`Auszeichnungen`, `Distinctions`],
    [`Talks`]: [`Vorträge`, `Interventions`],
    [`Conference paper`]: [`Konferenzbeitrag`, `Article de conférence`],

    // ---------- writing card update ----------
    [`5 posts`]: [`5 Beiträge`, `5 articles`],
    [`Notes on geospatial machine learning, Earth observation pipelines and what actually breaks when you scale them — from GNSS time series to hyperspectral imagery.`]: [`Notizen zu maschinellem Lernen für Geodaten, Erdbeobachtungs-Pipelines und dazu, was beim Skalieren tatsächlich schiefgeht – von GNSS-Zeitreihen bis zu Hyperspektralbildern.`, `Notes sur l'apprentissage automatique géospatial, les chaînes de traitement en observation de la Terre et ce qui casse vraiment quand on les met à l'échelle — des séries temporelles GNSS à l'imagerie hyperspectrale.`],
    [`Browse all posts`]: [`Alle Beiträge durchsuchen`, `Parcourir tous les articles`],
};

// Identical in every language: names, tools, paper titles, journals, institutions.
const I18N_SAME = [
    `Dev Shree Saini — Portfolio`,
    `Python`, `PyTorch`, `GNSS`, `ERA5`, `LSTM`, `XGBoost`, `U-Net`, `SAM2`, `SWAT`, `QGIS`, `AHP`,
    `Python, NumPy, Pandas, Git`, `PyTorch, XGBoost, CNNs, LSTMs`, `ERA5, NetCDF, GRIB, GNSS`, `QGIS, ArcGIS, GeoPandas, Rasterio`,
    `Sentinel-1 SAR`, `GBIF / sPlot`, `planttraits.earth`,
    `IIRS, ISRO`, `IIRS, ISRO · 2023`, `VIT Vellore`, `VIT University`, `VIT Vellore · 2023`, `VIT Vellore • 2023`,
    `Ahmedabad, Gujarat`, `2019 – 2023`, `2020-2023`, `2021`, `2022`, `2023`,
    `MapSAM2: Adapting SAM2 for Automatic Segmentation of Historical Map Images and Time Series`,
    `Land use/cover dynamics and associated impacts on eutrophication, land surface temperature, and ecosystem service values`,
    `Simulation of the hydraulic model HEC-RAS coupled with GIS and remote sensing to study the effect of river cross-section width in detecting flood-prone areas`,
    `The impact of short-duration precipitation events over the historic Cauvery Basin`,
    `Wetland Discharge Water Filtration of a Mesotrophic Lake`,
    `X. Xia, D. S. Saini et al.`, `D. S. Saini et al.`, `S. Ghosh, D. S. Saini et al.`, `A. C. Pereira, D. S. Saini et al.`,
    `IEEE Transactions on Geoscience and Remote Sensing • 2026`, `Estuaries and Coasts • 2025`,
    `Journal of the Geological Society of India • 2024`, `Scientific Reports, Nature • 2023`,
    `AICTE YUVAK Scholar`, `Swiss Geoscience Meeting`, `CSCE Annual Conference`, `Roorkee Water Conclave 2022`,
    `CSCE Annual Conference 2023`, `Swiss Geoscience Meeting 2025`,
    `C1 · IELTS`, `Hindi`, `Geospatial Insights`, `LinkedIn`, `GitHub`, `Google Scholar`,
];

(() => {
    const LANGS = ['en', 'de', 'fr'];
    const COLUMN = { de: 0, fr: 1 };
    const norm = (s) => String(s).replace(/\s+/g, ' ').trim();
    const dict = new Map(Object.entries(I18N_DICT).map(([k, v]) => [norm(k), v]));

    let lang = 'en';
    try {
        const saved = localStorage.getItem('portfolio-lang');
        if (LANGS.includes(saved)) lang = saved;
    } catch (e) { /* storage blocked: stay in English */ }

    const lookup = (s, l) => {
        if (l === 'en') return null;
        const row = dict.get(norm(s));
        return row ? row[COLUMN[l]] : null;
    };
    const t = (s) => {
        const v = lookup(s, lang);
        return v == null ? s : v;
    };

    // Remember each element's English content once. Icons at the very start or end
    // (e.g. <i class="fas fa-bolt"></i>NEWS) are kept around the translated text.
    const isEdge = (n) => (n.nodeType === 1 && n.tagName === 'I') || (n.nodeType === 3 && !n.textContent.trim());
    const outer = (nodes) => nodes.map(n => (n.nodeType === 1 ? n.outerHTML : '')).join('');
    const units = [...document.querySelectorAll('[data-i18n]')].map((el) => {
        const nodes = [...el.childNodes];
        let a = 0, b = nodes.length;
        while (a < b && isEdge(nodes[a])) a++;
        while (b > a && isEdge(nodes[b - 1])) b--;
        return { el, html: el.innerHTML, key: norm(el.textContent), lead: outer(nodes.slice(0, a)), trail: outer(nodes.slice(b)) };
    });

    const apply = (next) => {
        lang = LANGS.includes(next) ? next : 'en';
        units.forEach((u) => {
            const v = lookup(u.key, lang);
            u.el.innerHTML = v == null ? u.html : u.lead + v + (u.trail ? ' ' + u.trail : '');
        });
        document.documentElement.lang = lang;
        document.querySelectorAll('.lang-btn').forEach((btn) => {
            const on = btn.dataset.lang === lang;
            btn.classList.toggle('active', on);
            btn.setAttribute('aria-pressed', String(on));
        });
        try { localStorage.setItem('portfolio-lang', lang); } catch (e) { /* ignore */ }
        document.dispatchEvent(new CustomEvent('portfolio:language', { detail: { lang } }));
    };

    document.addEventListener('click', (e) => {
        const btn = e.target.closest('.lang-btn');
        if (!btn) return;
        e.preventDefault();
        apply(btn.dataset.lang);
    });

    window.i18n = { t, apply, get lang() { return lang; } };
    apply(lang);
})();
